version: '3.4'

services:
  web:
    build: .
    restart: always
    container_name: bryllup
    ports:
      - 5000:5000
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
